name: Create production image
on:
  push:
    branches: [prod]
  pull_request:
    branches: [prod]
    types: [closed]
env:
  environment: production
jobs:
  build:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Node js
        uses: actions/setup-node@v6
        with:
          node-version: 22.14.0
          cache: npm
      - name: Install packages
        run: npm install
      - name: build
        run: ng build --configuration ${{env.environment}}
  push-image:
    needs: build
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Prepare lowercase repository name
        run: echo "REPOSITORY_LC=${GITHUB_REPOSITORY,,}" >> "$GITHUB_ENV"
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ env.REPOSITORY_LC }}-${{env.environment}}:latest
